### ISSUE TITLE
permission denied for window type 2038

### ISSUE THREAD

**Issue by tolot27** [crowdin/mobile-sdk-android#103]
If I add the SDK to take screenshorts, my app crashes with the following exception:

```
2021-01-02 03:11:09.091 2475-2475/com.eveningoutpost.dexdrip E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eveningoutpost.dexdrip, PID: 2475
    java.lang.RuntimeException: Unable to resume activity {com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.Home}: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@ef03a02 -- permission denied for window type 2038
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@ef03a02 -- permission denied for window type 2038
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.crowdin.platform.util.UiUtilKt.createAuthDialog(UiUtil.kt:39)
        at com.crowdin.platform.Crowdin.authorize(Crowdin.kt:338)
        at com.eveningoutpost.dexdrip.Home.onResume(Home.java:1916)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7117)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

I've tested it with a Samsung Galaxy S7 running Android 8.0 as well as with a Pixel 2 API 27 emulator on Win 10 x64.

I know that the app/Crowdin SDK should request `ACTION_MANAGE_OVERLAY_PERMISSION` but it did not. On the Pixel, it is also not listed in the list of apps having overlay permission.

**Comment by crowdin-support** [comment]
Hello,

Happy New Year! Thank you for reaching Crowdin team.

Kindly note that our replies may be slower than usual (response time should
not exceed 24h though), also live chat will become active again from
January 2nd, 5AM UTC.

Any urgent inquiries will be resolved with the highest priority, inbox is
always monitored 🙄

All the best in 2021!

--
Sincerely yours,
Crowdin Team
{#HS:1384286841-137959#}

**Comment by tolot27** [comment]
I got it working by requesting the draw over other apps permission in my app and adding `<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />` to `AndroidManifest.xml`.

**Comment by Olena1234** [comment]
Hi there! We are glad to hear that it's working and please accept our apologies for not replying sooner!

**Comment by tolot27** [comment]
Maybe, the documentation can be improved to catch this?

I do not really know why it does not work using the implementation you provide with your SDK. Maybe, the initialization is not complete.
Currently, I do get only untagged screenshots and do not know, why.

**Comment by Olena1234** [comment]
Thank you for your suggestion! Let me check everything with the devs and come back to you on the matter

**Comment by CignoWeDigital** [comment]
Good morning. 
I face the same problem with permission. I tried to put `<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />` but still crash.
I'm using this version 1.4.2
The crash is generated when i call this on onCreate `Crowdin.authorize(this)`.

**Comment by andrii-bodnar** [comment]
Hi @CignoWeDigital, this issue was fixed in the 1.4.3 version. Could you please check if everything is ok now?

**Comment by CignoWeDigital** [comment]
hi @andrii-bodnar i checked and the bug seems fixed, I'm facing some problem with login, even if my password and email are correct it keep saying 401 Client authentication failed. I'm trying to figure out what the problem may be. Anyway thx for the fix :)

**Comment by andrii-bodnar** [comment]
@CignoWeDigital please check the `clientId`, `clientSecret` and redirect URL in OAuth configuration on Crowdin.

Redirect URL should match your App scheme. For example, for `<data android:scheme="crowdintest" />` redirect URL in Crowdin should be `crowdintest://`

Also, if you are using crowdin.com, not Crowdin Enterprise, `organization_name` in the SDK config should be `null`.

**Comment by CignoWeDigital** [comment]
@andrii-bodnar thx a lot for the advice, I managed to fix everything and now it works fine. Thx and happy coding :)
