### ISSUE TITLE
Target API 31 support

### ISSUE THREAD

**Issue by oleksandrbalan-etn** [crowdin/mobile-sdk-android#153]
**Describe the bug**
In version 1.4.7 the old work manager version is used (v2.5.0), which causes:

```
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

See https://issuetracker.google.com/issues/194108978#comment13

**To Reproduce**
1. Create a project with target API 31
2. Integrate SDK v1.4.7
3. Launch an app

**Expected behavior**
Application will not crash.

**Comment by oleksandrbalan-etn** [comment]
Currently it is possible to force new version of the Work Manager:
```
implementation("androidx.work:work-runtime-ktx:2.7.0")
```
