### ISSUE TITLE
Crowdin SDK: Crash while implementing Real-time updates

### ISSUE THREAD

**Issue by Afolayan** [crowdin/mobile-sdk-android#156]
**Describe the bug**

**Expected behavior**
This occurred while implementing Real-Time Preview and Screenshots features. After logging in, the app crashes and returns the error below.

**Smartphone (please complete the following information):**
 - Device: [Samsung A30]
 - OS: [e.g. Android 11]
 - Crowdin SDK version: 1.4.8

**Error log**
```
FATAL EXCEPTION: OkHttp Dispatcher
    java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.RealCall.enterNetworkInterceptorExchange(RealCall.kt:229)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:66)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.crowdin.platform.data.remote.interceptor.HeaderInterceptor.intercept(HeaderInterceptor.kt:19)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.crowdin.platform.data.remote.interceptor.SessionInterceptor.intercept(SessionInterceptor.kt:36)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by tattiza** [comment]
Hi there!
Already shared it with the tech team, once we have any updates - we'll let you know

**Comment by Afolayan** [comment]
Checking the OkHttp Interceptor repo: Seems there's an issue created [here](https://github.com/square/okhttp/issues/4986)
Maybe it could help?

**Comment by tattiza** [comment]
Thanks!
We'll have a look on it
