### ISSUE TITLE
Realtime preview crash

### ISSUE THREAD

**Issue by exxKx** [crowdin/mobile-sdk-android#180]
Crash happened on every app start if realtime preview enabled. 
crowdin versions: 1.5.4 - 1.5.5

```
 E/AndroidRuntime: FATAL EXCEPTION: LocalWorkThreadPool-23
    java.util.ConcurrentModificationException
        at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:807)
        at java.util.WeakHashMap$EntryIterator.next(WeakHashMap.java:846)
        at java.util.WeakHashMap$EntryIterator.next(WeakHashMap.java:844)
        at java.util.WeakHashMap.putAll(WeakHashMap.java:566)
        at java.util.Collections$SynchronizedMap.putAll(Collections.java:2645)
        at com.crowdin.platform.transformer.ViewTransformerManager.getVisibleViewsWithData(ViewTransformerManager.kt:70)
        at com.crowdin.platform.realtimeupdate.EchoWebSocketListener.saveMatchedTextViewWithMappingId(EchoWebSocketListener.kt:86)
        at com.crowdin.platform.realtimeupdate.EchoWebSocketListener.resubscribeView(EchoWebSocketListener.kt:60)
        at com.crowdin.platform.realtimeupdate.EchoWebSocketListener.access$resubscribeView(EchoWebSocketListener.kt:26)
        at com.crowdin.platform.realtimeupdate.EchoWebSocketListener$onOpen$1.onChange$lambda-0(EchoWebSocketListener.kt:47)
        at com.crowdin.platform.realtimeupdate.EchoWebSocketListener$onOpen$1.$r8$lambda$4ex4arbJg14-n4M0d3eoz8P9RjE(Unknown Source:0)
        at com.crowdin.platform.realtimeupdate.EchoWebSocketListener$onOpen$1$$ExternalSyntheticLambda0.run(Unknown Source:10)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

```

**Comment by andrii-bodnar** [comment]
Hi @exxKx!

Could you please confirm that it's reproducible on the [Example project](https://github.com/crowdin/mobile-sdk-android/wiki/Example-Project)?

**Comment by exxKx** [comment]
Not reproduced on the example

**Comment by andrii-bodnar** [comment]
@exxKx Could you please provide some steps for us to be able to easily reproduce this issue? It will help us to fix this

**Comment by exxKx** [comment]
1. Set  .withRealTimeUpdates()
2. Launch app
3. Login in crowdin

crash

**Comment by andrii-bodnar** [comment]
@exxKx also, please provide the following details:
- Device where you're running your app
- Android Version
- Crowdin Android SDK version
- Send us your distribution hash using [this contact form](https://crowdin.com/contacts) and mention this issue for reference

**Comment by exxKx** [comment]
Pixel 4a 5g
Android 13 / api33

**Comment by exxKx** [comment]
also crashes on 
HUAWEI MAR-LX1M
Android10, api29

**Comment by andrii-bodnar** [comment]
Couldn't reproduce, needs [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by laszlomagyardocler** [comment]
Hi!

For me, the issue is still reproducible with version 1.5.9. I'm using the SDK and the controls library too and it randomly crashes (mostly when I switch fragments):
<img width="1090" alt="Screenshot 2023-06-28 at 16 43 44" src="https://github.com/crowdin/mobile-sdk-android/assets/132657310/60a6bd96-3620-42ac-b3ce-ba05601edee3">

I'm using this config:
<img width="403" alt="Screenshot 2023-06-28 at 16 45 49" src="https://github.com/crowdin/mobile-sdk-android/assets/132657310/de1b3851-a5f6-46bb-ae39-0a10102a280d">
