### ISSUE TITLE
SDK breaks styles

### ISSUE THREAD

**Issue by sweid337** [crowdin/mobile-sdk-android#75]
**Describe the bug**

After adding the SDK to the application, the dialog styles _(AlertDialog, BottomSheetDialog, etc.)_ broke. 

This is how I implemeted base activity for my app.
```
abstract class CrowdInActivity: AppCompatActivity() {
    override fun attachBaseContext(base: Context) {
        super.attachBaseContext(Crowdin.wrapContext(base))
    }
}
```

I'm using the latest version of SDK (1.2.0)

**Screenshots**

<table>
   <tr><td>SDK Enabled</td><td>SDK Disabled</td></tr>
   <tr><td><img src="https://user-images.githubusercontent.com/56417671/96546929-e2e47100-12b3-11eb-9dee-71e95f0af9de.jpg" height="500"/></td><td><img src="https://user-images.githubusercontent.com/56417671/96546934-e546cb00-12b3-11eb-943e-39863c3fd261.jpg" height="500"/></td></tr>
   <tr><td><img src="https://user-images.githubusercontent.com/56417671/96546932-e4159e00-12b3-11eb-87cb-9319deabea4d.jpg" height="500"/></td><td><img src="https://user-images.githubusercontent.com/56417671/96546936-e5df6180-12b3-11eb-88f9-ccaed7e80570.jpg" height="500"/></td></tr>
</table>

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android X

**Comment by David-Hackro** [comment]
which `appcompat` version you are use?

**Comment by MykhailoNester** [comment]
Hello, @sergeyboganec thanks for your report. My first assumption that issue is related to material-design or appCompat version difference.

SDK uses(UI related libs):

```
    implementation "androidx.appcompat:appcompat:1.1.0"
    implementation "com.google.android.material:material:1.1.0"
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
```

One of solutions might be:
- migrate to new version 
- specify version in your project like this: 

```
    implementation ('com.google.android.material:material') {
        version {
            strictly '1.1.0' // your version
        }
    }
```
It will prevent usage of newer lib version from SDK in your project. 

In case issue still persist please send me your library versions. Also would be helpful to see how is your main style looks like.

**Comment by TwoEightNine** [comment]
Hi, @MykhailoNester! Thank you for your assumption. I faced with the same issue and your solution didn't help. I updated specified libraries and nothing changed. Crowdin SDK v1.2.1

**Comment by David-Hackro** [comment]
"Material Components" use a wrapper over the context (`ContextThemeWrapper`), and crowdin sdk apply another wrapper over context (`ContextThemeWrapper`).

It's possible that altered the themes tree?

**Comment by Olena1234** [comment]
Hi @TwoEightNine and @David-Hackro ! Thank you for the additional information! We will check the details and come back to you on the matter

**Comment by MykhailoNester** [comment]
@TwoEightNine @David-Hackro 
New 1.3.0 version was released. We've updated dependencies and also the way how to wrap context (replace old `attachBaseContext` method only if AppCompat >= 1.2.0)

```
BaseActivity:
override fun getDelegate() = BaseContextWrappingDelegate(super.getDelegate())
```
In case issue still reproducible with new version I'll need more information to reproduce it locally:
- Crowdin.init() method, which features are enabled?
- library versions related to UI;
- what `android:theme` is used in your app(application class and activity if applicable). In case it is custom - parent name should be enough;
- part of xml which shows some component. For example button/dialog that changes during SDK on/off; And if component has own style please share it too;

Crowdin context wrapping mechanism only used to inject own implementation of Resource object. No changes with context, it goes straight to `ContextWrapper(Context base)` constructor. 

Second area of investigation it is `CrowdinLayoutInflater` - which tries to apply some transformations to the newly created views. It shouldn't change styles and works only with a text but I'll investigate it more.

**Comment by David-Hackro** [comment]
@sergeybogdanec do you have any news about this problem? i continue with similar issue with material.

**Comment by AGuminskyi** [comment]
@MykhailoNester Hi! Faced with the same issue that @David-Hackro mentioned above (`the MaterialAlertDialogBuilder break the app`). When I try to show `MaterialAlertDialogBuilder` it throws an exception: 

> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: some_app_name, PID: 12908
    android.view.InflateException: Binary XML file line #25 in some_app_name:layout/mtrl_alert_dialog: Binary XML file line #27: You must supply a layout_width attribute.
    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #27: You must supply a layout_width attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:862)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7962)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8160)
        at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2023)
        at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1917)
        at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:89)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
        at android.app.Dialog.show(Dialog.java:315)
        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)

Sends an information for you about project and Crowdin setup:

- Crowdin version: 
```crowdin_version = "1.3.2"```

- Setup in activity: 
```override fun getDelegate(): AppCompatDelegate = BaseContextWrappingDelegate(super.getDelegate())```

- Crowdin.init() method, which features are enabled?

```    
Crowdin.init(
    applicationContext,
    CrowdinConfig.Builder()
        .withDistributionHash("my hash code")
            .build()
    )
```
   
-  library versions related to UI:
```
appcompat_version = '1.2.0'
material_version = '1.3.0-beta01'
```
        
- what android:theme is used in your app(application class and activity if applicable). In case it is custom - parent name should be enough;
```<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">```

- part of xml which shows some component. For example button/dialog that changes during SDK on/off; And if component has own style please share it too;
```
val alertDialog = MaterialAlertDialogBuilder(context)
            .setTitle(title)
            .setMessage(message)
            .setPositiveButton(positive) { dialog, _ ->
               // no matter what here
            }
            .setNegativeButton(negative) { dialog, _ ->
                // no matter what here
            }
        return alertDialog.show()
```

Notice: there is no issues with simple `AlertDialog.Builder`.

Please let me know if you need more information.
Have a nice day! :)

**Comment by David-Hackro** [comment]
@AGuminskyi i have the same issue, and only have this problem when enable de crowdin sdk, maybe the problem is relate with the wrap context, here you cand find a question in [stackoverflow](https://stackoverflow.com/questions/64898178/contextwrapper-override-contextthemewrapper)

**Comment by andrii-bodnar** [comment]
Hi, @sergeybogdanec, @David-Hackro, @AGuminskyi, @TwoEightNine !

We have just released a new version (1.3.4) with the fix, could you please check if everything is ok now?

**Comment by David-Hackro** [comment]
I confirmed, the change works! Thanks! 👏

**Comment by sergeybogdanec** [comment]
Hi, @andrii-bodnar. Yes, it works great now! Thanks! Sorry for delay.
