### ISSUE TITLE
UnknownFormatConversionException when trying to set text with `%` at the end

### ISSUE THREAD

**Issue by TwoEightNine** [crowdin/mobile-sdk-android#83]
**Describe the bug**
Crowdin SDK crashes when trying to set text with `%` at the end:
```kotlin
myTextView.text = "10%"
```

On the other hand, when trying to set `%%`, the SDK is not crashing but it is not what I expect to see in UI.

**To Reproduce**
1. Implement and initialize Crowdin SDK
2. Try to set text with `%` at the end

**Expected behavior**
Crowdin SDK doesn't crash and shows text correctly.

**Smartphone (please complete the following information):**
 - Xiaomi Mi A3 (Android 10)
 - Huawei P20 Lite (Android 8.0)

**Stacktrace**
```
java.util.UnknownFormatConversionException: Conversion = 'End of String'
        at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2641)
        at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2602)
        at java.util.Formatter.parse(Formatter.java:2557)
        at java.util.Formatter.format(Formatter.java:2504)
        at java.util.Formatter.format(Formatter.java:2458)
        at java.lang.String.format(String.java:2770)
        at com.crowdin.platform.data.local.MemoryLocalRepository.searchInPlurals(MemoryLocalRepository.kt:160)
        at com.crowdin.platform.data.local.MemoryLocalRepository.searchInResources(MemoryLocalRepository.kt:147)
        at com.crowdin.platform.data.local.MemoryLocalRepository.getTextData(MemoryLocalRepository.kt:129)
        at com.crowdin.platform.data.local.SharedPrefLocalRepository.getTextData(SharedPrefLocalRepository.kt:77)
        at com.crowdin.platform.data.DataManager.provideTextMetaData(DataManager.kt:47)
        at com.crowdin.platform.transformer.TextViewTransformer$Watcher.afterTextChanged(TextViewTransformer.kt:104)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:9605)
        at android.widget.TextView.setText(TextView.java:5496)
        at android.widget.TextView.setText(TextView.java:5343)
        at android.widget.TextView.setText(TextView.java:5300)
```

**Comment by Natalia936** [comment]
We're sorry for that inconvenience, our team will take a look as fast as possible
